version: "3"
services:
  redis:
    image: redis:7.2.3
    container_name: tfp-redis-dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    environment:
      - REDIS_PORT=6379

  mongo:
    image: mongo
    restart: always
    container_name: tfp-mongo-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
